version: '3.1'

services:

  api:
    build: 
      context: .
      dockerfile: ./src/Dotnet.CDC.Api/Dockerfile
    ports:
      - 5000:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      kafkaServer: kafka:9092
      kafkaTopicMySql: mysql.mystore.products
    depends_on:
      - kafka

